# Brightness up
- alias: Rotary Lamp Brightness Up
  mode: queued
  trigger:
    - platform: mqtt
      topic: inputs/rotary/lamp
  condition:
    - condition: template
      value_template: "{{ trigger.payload.startswith('brightness_up') }}"
  action:
    - variables:
        step: "{{ (trigger.payload.split(':')[1] | int) if ':' in trigger.payload else 5 }}"
    - service: light.turn_on
      target:
        entity_id: light.yx_room_light
      data:
        brightness_step_pct: "{{ step }}"

# Brightness down
- alias: Rotary Lamp Brightness Down
  mode: queued
  trigger:
    - platform: mqtt
      topic: inputs/rotary/lamp
  condition:
    - condition: template
      value_template: "{{ trigger.payload.startswith('brightness_down') }}"
  action:
    - variables:
        step: "{{ (trigger.payload.split(':')[1] | int) if ':' in trigger.payload else 5 }}"
    - service: light.turn_on
      target:
        entity_id: light.yx_room_light
      data:
        brightness_step_pct: "{{ 0 - step }}"

# Toggle on press
- alias: Rotary Lamp Toggle
  trigger:
    - platform: mqtt
      topic: inputs/rotary/lamp
      payload: "toggle"
  action:
    - service: light.toggle
      target:
        entity_id: light.yx_room_light
